[2022-07-28 13:21:51,527] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.story_user scheduled__2022-07-22T00:00:00+00:00 [queued]>
[2022-07-28 13:21:51,534] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.story_user scheduled__2022-07-22T00:00:00+00:00 [queued]>
[2022-07-28 13:21:51,535] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 13:21:51,537] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-28 13:21:51,538] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 13:21:51,547] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): story_user> on 2022-07-22 00:00:00+00:00
[2022-07-28 13:21:51,552] {standard_task_runner.py:52} INFO - Started process 97 to run task
[2022-07-28 13:21:51,555] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'story_user', 'scheduled__2022-07-22T00:00:00+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpd0jkhpu3', '--error-file', '/tmp/tmpcnpfo8cm']
[2022-07-28 13:21:51,557] {standard_task_runner.py:80} INFO - Job 151: Subtask story_user
[2022-07-28 13:21:51,597] {task_command.py:369} INFO - Running <TaskInstance: user_processing.story_user scheduled__2022-07-22T00:00:00+00:00 [running]> on host e755cbaa46dc
[2022-07-28 13:21:51,641] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=story_user
AIRFLOW_CTX_EXECUTION_DATE=2022-07-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-22T00:00:00+00:00
[2022-07-28 13:21:51,652] {postgres.py:127} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2022-07-28 13:21:51,660] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-07-28 13:21:51,666] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/user_processing.py", line 33, in _store_user
    filename='/tmp/processed_user.csv'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 135, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.BadCopyFileFormat: missing data for column "lastname"
CONTEXT:  COPY users, line 2: ""

[2022-07-28 13:21:51,676] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=user_processing, task_id=story_user, execution_date=20220722T000000, start_date=20220728T132151, end_date=20220728T132151
[2022-07-28 13:21:51,685] {standard_task_runner.py:97} ERROR - Failed to execute job 151 for task story_user (missing data for column "lastname"
CONTEXT:  COPY users, line 2: ""
; 97)
[2022-07-28 13:21:51,730] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-28 13:21:51,769] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
