[2022-07-21 06:04:25,267] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.dbt_run scheduled__2022-07-20T00:00:00+00:00 [queued]>
[2022-07-21 06:04:25,281] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.dbt_run scheduled__2022-07-20T00:00:00+00:00 [queued]>
[2022-07-21 06:04:25,282] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 06:04:25,282] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-21 06:04:25,284] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 06:04:25,298] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dbt_run> on 2022-07-20 00:00:00+00:00
[2022-07-21 06:04:25,307] {standard_task_runner.py:52} INFO - Started process 300 to run task
[2022-07-21 06:04:25,313] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'dbt_run', 'scheduled__2022-07-20T00:00:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpwd6ikbr5', '--error-file', '/tmp/tmptr2lqwye']
[2022-07-21 06:04:25,316] {standard_task_runner.py:80} INFO - Job 87: Subtask dbt_run
[2022-07-21 06:04:25,387] {task_command.py:369} INFO - Running <TaskInstance: user_processing.dbt_run scheduled__2022-07-20T00:00:00+00:00 [running]> on host b03e8595b275
[2022-07-21 06:04:25,445] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2022-07-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-20T00:00:00+00:00
[2022-07-21 06:04:25,447] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-21 06:04:25,449] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n        cd /opt/***/dbt &&\n        dbt run --profiles-dir /opt/***/dbt\n        ']
[2022-07-21 06:04:25,460] {subprocess.py:85} INFO - Output:
[2022-07-21 06:04:25,463] {subprocess.py:92} INFO - bash: line 3: dbt: command not found
[2022-07-21 06:04:25,464] {subprocess.py:96} INFO - Command exited with return code 127
[2022-07-21 06:04:25,477] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-21 06:04:25,480] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=user_processing, task_id=dbt_run, execution_date=20220720T000000, start_date=20220721T060425, end_date=20220721T060425
[2022-07-21 06:04:25,489] {standard_task_runner.py:97} ERROR - Failed to execute job 87 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 300)
[2022-07-21 06:04:25,533] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-21 06:04:25,557] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
