[2022-07-28 13:55:32,335] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: glue_af_pipeline.load_csv manual__2022-07-28T13:55:29.469823+00:00 [queued]>
[2022-07-28 13:55:32,345] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: glue_af_pipeline.load_csv manual__2022-07-28T13:55:29.469823+00:00 [queued]>
[2022-07-28 13:55:32,347] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 13:55:32,348] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-28 13:55:32,350] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 13:55:32,361] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_csv> on 2022-07-28 13:55:29.469823+00:00
[2022-07-28 13:55:32,366] {standard_task_runner.py:52} INFO - Started process 1196 to run task
[2022-07-28 13:55:32,369] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'glue_af_pipeline', 'load_csv', 'manual__2022-07-28T13:55:29.469823+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/loaddata_rds.py', '--cfg-path', '/tmp/tmpv5yxez6p', '--error-file', '/tmp/tmpn_cxs7uk']
[2022-07-28 13:55:32,384] {standard_task_runner.py:80} INFO - Job 156: Subtask load_csv
[2022-07-28 13:55:32,440] {task_command.py:371} INFO - Running <TaskInstance: glue_af_pipeline.load_csv manual__2022-07-28T13:55:29.469823+00:00 [running]> on host dd3800c43a8f
[2022-07-28 13:55:32,492] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=glue_af_pipeline
AIRFLOW_CTX_TASK_ID=load_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-07-28T13:55:29.469823+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-28T13:55:29.469823+00:00
[2022-07-28 13:55:32,495] {postgres.py:127} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /Telco-Customer-Churn.csv
[2022-07-28 13:55:32,498] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/loaddata_rds.py", line 20, in _store_user
    filename='/Telco-Customer-Churn.csv'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 129, in copy_expert
    with open(filename, 'w'):
PermissionError: [Errno 13] Permission denied: '/Telco-Customer-Churn.csv'
[2022-07-28 13:55:32,509] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=glue_af_pipeline, task_id=load_csv, execution_date=20220728T135529, start_date=20220728T135532, end_date=20220728T135532
[2022-07-28 13:55:32,518] {standard_task_runner.py:97} ERROR - Failed to execute job 156 for task load_csv ([Errno 13] Permission denied: '/Telco-Customer-Churn.csv'; 1196)
[2022-07-28 13:55:32,559] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-28 13:55:32,589] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
