[2022-07-21 17:38:25,282] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.dbt_run manual__2022-07-21T17:38:19.421407+00:00 [queued]>
[2022-07-21 17:38:25,290] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.dbt_run manual__2022-07-21T17:38:19.421407+00:00 [queued]>
[2022-07-21 17:38:25,291] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 17:38:25,293] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-21 17:38:25,294] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 17:38:25,304] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dbt_run> on 2022-07-21 17:38:19.421407+00:00
[2022-07-21 17:38:25,309] {standard_task_runner.py:52} INFO - Started process 8008 to run task
[2022-07-21 17:38:25,312] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'dbt_run', 'manual__2022-07-21T17:38:19.421407+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmplrxlnbpb', '--error-file', '/tmp/tmpb8rryyey']
[2022-07-21 17:38:25,315] {standard_task_runner.py:80} INFO - Job 104: Subtask dbt_run
[2022-07-21 17:38:25,358] {task_command.py:369} INFO - Running <TaskInstance: user_processing.dbt_run manual__2022-07-21T17:38:19.421407+00:00 [running]> on host e755cbaa46dc
[2022-07-21 17:38:25,413] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2022-07-21T17:38:19.421407+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-21T17:38:19.421407+00:00
[2022-07-21 17:38:25,416] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-21 17:38:25,417] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n        cd dbt &&\n        dbt run --profiles-dir .\n        ']
[2022-07-21 17:38:25,429] {subprocess.py:85} INFO - Output:
[2022-07-21 17:38:25,431] {subprocess.py:92} INFO - bash: line 2: cd: dbt: No such file or directory
[2022-07-21 17:38:25,433] {subprocess.py:96} INFO - Command exited with return code 1
[2022-07-21 17:38:25,447] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-07-21 17:38:25,450] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=user_processing, task_id=dbt_run, execution_date=20220721T173819, start_date=20220721T173825, end_date=20220721T173825
[2022-07-21 17:38:25,461] {standard_task_runner.py:97} ERROR - Failed to execute job 104 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 8008)
[2022-07-21 17:38:25,487] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-21 17:38:25,513] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
