[2022-07-20 04:52:16,799] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.story_user scheduled__2022-07-15T00:00:00+00:00 [queued]>
[2022-07-20 04:52:16,808] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.story_user scheduled__2022-07-15T00:00:00+00:00 [queued]>
[2022-07-20 04:52:16,809] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 04:52:16,810] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-20 04:52:16,811] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 04:52:16,821] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): story_user> on 2022-07-15 00:00:00+00:00
[2022-07-20 04:52:16,826] {standard_task_runner.py:52} INFO - Started process 92 to run task
[2022-07-20 04:52:16,829] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'story_user', 'scheduled__2022-07-15T00:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpda0omdmg', '--error-file', '/tmp/tmpak3e9b2q']
[2022-07-20 04:52:16,831] {standard_task_runner.py:80} INFO - Job 63: Subtask story_user
[2022-07-20 04:52:16,876] {task_command.py:369} INFO - Running <TaskInstance: user_processing.story_user scheduled__2022-07-15T00:00:00+00:00 [running]> on host 4800f8aada3e
[2022-07-20 04:52:16,925] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=story_user
AIRFLOW_CTX_EXECUTION_DATE=2022-07-15T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-15T00:00:00+00:00
[2022-07-20 04:52:16,927] {postgres.py:127} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2022-07-20 04:52:16,934] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-07-20 04:52:16,941] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/user_processing.py", line 30, in _store_user
    filename='/tmp/processed_user.csv'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 135, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.BadCopyFileFormat: missing data for column "lastname"
CONTEXT:  COPY users, line 2: "e.com"

[2022-07-20 04:52:16,951] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=user_processing, task_id=story_user, execution_date=20220715T000000, start_date=20220720T045216, end_date=20220720T045216
[2022-07-20 04:52:16,959] {standard_task_runner.py:97} ERROR - Failed to execute job 63 for task story_user (missing data for column "lastname"
CONTEXT:  COPY users, line 2: "e.com"
; 92)
[2022-07-20 04:52:17,002] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-20 04:52:17,027] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
